"""
IoT Module - Cấu hình Digital Twin cho Smart Building
"""

from .devices import (
    ROOM_CONFIG,
    DEVICES_TO_REGISTER,
    ALERT_EVENT_TEMPLATE,
    ROBOT_ACTION_TEMPLATE,
    DEVICE_STATUSES,
    CONNECTIVITY_STATUSES,
    AIR_QUALITY_STATUSES,
    SAFETY_STATUSES,
    ALERT_SEVERITIES,
    ROBOT_STATUSES,
    EMERGENCY_LEVELS
)

__all__ = [
    "ROOM_CONFIG",
    "DEVICES_TO_REGISTER",
    "ALERT_EVENT_TEMPLATE",
    "ROBOT_ACTION_TEMPLATE",
    "DEVICE_STATUSES",
    "CONNECTIVITY_STATUSES",
    "AIR_QUALITY_STATUSES",
    "SAFETY_STATUSES",
    "ALERT_SEVERITIES",
    "ROBOT_STATUSES",   
    "EMERGENCY_LEVELS"
]